stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

.default-job-template:
  image: eclipse-temurin:25-jdk
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq maven
    - mvn -v
    - java -version

build:
  stage: build
  extends: .default-job-template
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  extends: .default-job-template
  script:
    - mvn $MAVEN_CLI_OPTS test