stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .m2/repository

before_script:
  - echo "Using Java version:"
  - java -version
  - echo "Using Maven version:"
  - mvn -v

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 week
  only:
    - develop
    - merge_requests
    - feature/*

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - develop
    - merge_requests
    - feature/*

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - master